environment:
  access_token:
    secure: 0skQZS3raRtshDg3zZ8vbku0Zi0p5o+AeU0Jr/SQugHK/nA7Y40YOvfNoPb9eTVR

install:
- ps: >-
    Install-PackageProvider -Name NuGet -Force
    
    Install-Module -Name PSScriptAnalyzer -Force
    
    Install-Module -Name Pester -Force

build: off
test_script:
- ps: >- 
    .\CI\build.ps1
    
on_success:  
- git config --global credential.helper store
- ps: Add-Content "$HOME\.git-credentials" "https://$($env:GitToken):x-oauth-basic@github.com`n"
- git config --global user.email "build@appveyor.com"
- git config --global user.name "Appveyor"
- git checkout %APPVEYOR_REPO_BRANCH%
- git add *.psd1
- git add *.md
- git commit -m "[skip ci] AppVeyor Build %APPVEYOR_BUILD_VERSION%"
- git push 